try{var pe={staticStorageUrl:(_peSd.config&&_peSd.config.staticStorageUrl)?_peSd.config.staticStorageUrl:'https://assetscdn.pushengage.com',initSw:function(maincallback){if('serviceWorker'in navigator&&_peE.bWSupport&&_peE.sT=='https'){_peD.widget.resetClosedCookie();if(_peD.merchantSettings.sm('workerStatus')){var options={};var scope=false;if(_peD.merchantSettings.sm('scope')){options.scope="/";scope=true;}
navigator.serviceWorker.register(_peD.merchantSettings.sm('worker'),options).then(function(registration){if(scope){return pe.pushSub(maincallback);}
setTimeout(function(){pe.pushSub(maincallback);},3000);}).catch(function(e){throw e;});}
else{pe.pushSub(maincallback);}}},overlay:{addHtml:function(){var overlayId=_peD.getId("PE-chicklet-inst-modal");if(!overlayId&&_peE.dT=="desktop"){if(_peSd.overlay.status){var body=document.getElementsByTagName("BODY")[0];body.insertAdjacentHTML('beforeend',_peSd.overlay.style);body.insertAdjacentHTML('beforeend',_peSd.overlay.html);var overlayClose=_peD.getId("pushengage-overlay-close");var overlayImageId=_peD.getId("pe-overlay-reminder-image");var overlayReminderImage=pe.staticStorageUrl+'/site_assets/img/overlay-reminder-chrome.png';var overlayArrowImage=_peD.getId("pe-overlay-backdrop-arrow-image");if(_peE.bW.name==="Firefox"){overlayReminderImage=pe.staticStorageUrl+'/site_assets/img/overlay-reminder-firefox.png';}
if(_peD.getInputUrl('intermediate')&&overlayArrowImage){overlayArrowImage.style.width='350px';overlayArrowImage.style.margin='0px';}
if(overlayImageId){overlayImageId.src=overlayReminderImage;}
if(_peE.bW.name=='Edge'&&_peE.bW.version<"79"){var oNT=_peD.getId("pe-pc-notice-text");if(overlayArrowImage){overlayArrowImage.style.top='unset';overlayArrowImage.style.bottom='135px';overlayArrowImage.style.transform='rotate(180deg)';}
if(_peD.getInputUrl('intermediate')&&overlayArrowImage){overlayArrowImage.style.left='unset';}
if(oNT){oNT.style.bottom="unset";oNT.style.top="0px";}}
if(overlayClose){overlayClose.addEventListener('click',function(){pe.overlay.hideHtml();})}}
else if(_peSd.site.powBy!=1){var body=document.getElementsByTagName("BODY")[0];body.insertAdjacentHTML('beforeend',_peSd.overlay.powBycss);body.insertAdjacentHTML('beforeend',_peSd.overlay.powByHtml);if(_peD.getInputUrl('intermediate')){var id=_peD.getId("pe-overlay-powby");if(id)id.href="https://www.pushengage.com?utm_source="+_peSd.site.allowedDomain[0]+"&utm_medium=referral&utm_campaign=push_window";}}}},hideHtml:function(){_peD.rvHtml(_peD.getId('pe-overlay-powby'));_peD.rvHtml(_peD.getId('pe-overlay-backdrop'));_peD.rvHtml(_peD.getId('pe-overlay-backdrop-style'));},},apiValid:function(){var valid=true;if(!_peE.checkApiValid||typeof _peD!=='object'||typeof _peSd!=='object'||typeof _peE!=='object'||(_peE.sT=='http'&&_peE.bW.name!="Safari")||(_peD.deviceToken.cookie()&&Notification.permission=="granted"&&_peD.cookie.get('PushSubscriberStatus')!='UNSUBSCRIBED'))valid=false;if(_peE.refToken)valid=true;return valid;},vapidNotSupportBw:function(){return((_peE.bW.name=="Chrome"&&_peE.bW.version<52)||(_peE.bW.name=="Firefox"&&_peE.bW.version<46))?true:false;},isGcm:function(endpoint){gcm=endpoint.indexOf('android.googleapis.com/gcm')>-1||endpoint.indexOf('updates.push.services.mozilla.com/wpush/v1')>-1
return gcm;},bwUnsubscribe:function(callback){if('serviceWorker'in navigator){_peD.bwUnsubscribeAPI(function(res){pe.subscribe(callback)});}},pushSub:function(maincallback){var subApi;if(_peD.merchantSettings.sm('scope')){subApi=navigator.serviceWorker.ready;}
else{subApi=navigator.serviceWorker.register(_peD.merchantSettings.sm('worker'));}
subApi.then(function(reg){var subOptions={userVisibleOnly:true};if(!pe.vapidNotSupportBw()){subOptions.applicationServerKey=_peD.publicKey(_peSd.site.vapidPubKey);}
reg.pushManager.subscribe(subOptions).then(function(sub){try{var pe_sub=JSON.parse(JSON.stringify(sub));}
catch(e){return;}
_peD.getDeviceTokenFromEndPoint(pe_sub.endpoint,'init');pe_sub['project_id']=_peSd.gcm.projectId;if(!pe.vapidNotSupportBw()&&!pe.isGcm(pe_sub.endpoint)){pe_sub['vapid_public_key']=_peSd.site.vapidPubKey;}
pe.permissionGranted(pe_sub,maincallback);}).catch(function(e){if(e.message.indexOf('unsubscribe then resubscribe')!=-1)
pe.bwUnsubscribe(maincallback);else
pe.permissionDefault(maincallback);});});},subscribe:function(maincallback){if(!pe.apiValid()){if(_peD.getInputUrl('intermediate')){pe.sendDataToBrowser();}
return;}
_peD.pvtBw(function(pvtBw){if(!pvtBw){if(!_peD.userPerDenied())
switch(_peE.bW.name){case"Safari":if('safari'in window&&'pushNotification'in window.safari){var perD=window.safari.pushNotification.permission(_peSd.safari.pushId);if(perD.permission==='default'||perD.permission==='granted'){_peD.widget.resetClosedCookie();pe.safariPermission(perD,function(perD){if(perD.permission==='denied'){pe.permissionDenied(maincallback);}
else if(perD.permission==='granted')
{pe.overlay.hideHtml();_peD.deviceToken.value=perD.deviceToken;pe.permissionGranted({endpoint:_peD.deviceToken.value,project_id:_peSd.safari.pushId},maincallback);}});}}
break;default:if(Notification.permission=='default'){pe.overlay.addHtml();}
if(pe.vapidNotSupportBw()){var link=document.createElement('link');link.rel='manifest';link.href=_peD.merchantSettings.sm('manifest');document.getElementsByTagName("head")[0].appendChild(link);}
if(pe.optinSubscriptionReminder.status()){pe.optinSubscriptionReminder.reminder();}
Notification.requestPermission().then(function(status){pe.optinSubscriptionReminder.clearReminder();switch(status){case"default":pe.permissionDefault(maincallback);break;case"denied":pe.permissionDenied(maincallback);break;case"granted":pe.overlay.hideHtml();pe.initSw(maincallback);}}).catch(function(e){pe.optinSubscriptionReminder.clearReminder();});break;}
else{_peD.widget.addBoxHtml(maincallback);}}});},safariPermission:function(permissionData,callback){window.safari.pushNotification.requestPermission(_peSd.api.safariApi,_peSd.safari.pushId,{"app_id":_peSd.site.sK},callback);},permissionDenied:function(maincallback){if(_peE.sT=="https"&&_peE.swSupport==1)
_peD.widget.addHtml(maincallback);pe.overlay.hideHtml();if(_peD.subOptinType()==4){_peD.optinAnalytics({block_1:true,optin_1:true});}
else{_peD.optinAnalytics({allow_1:true,optin_1:true,block_2:true,optin_2:true});}
_peD.cookie.set([['PushSubscriberStatus','DENIED',_peD.cookie.optinHide,'/','cookie'],['peclosed',true,_peE.cookie.optinHide,'/','cookie'],['PushOptinReminder',JSON.stringify({}),false,'/','local'],]);if(typeof(maincallback)==='function')
maincallback({statuscode:2,status:"DENIED",message:"User denied push notification"});if(_peD.getInputUrl('intermediate')){pe.sendDataToBrowser();}},permissionDefault:function(maincallback){pe.overlay.hideHtml();if(_peD.subOptinType()==4){_peD.optinAnalytics({close_1:true,optin_1:true});}
else{_peD.optinAnalytics({allow_1:true,optin_1:true,close_2:true,optin_2:true});}
if(_peE.cookie.optinHide!=0&&!pe.isFirefoxPermissionDefaultQuiterUI())
_peD.cookie.set([['PushSubscriberStatus','CLOSED',_peE.cookie.optinHide,'/','cookie'],['peclosed',true,_peE.cookie.optinHide,'/','cookie'],['PushOptinReminder',JSON.stringify({}),false,'/','local'],]);if(typeof(maincallback)==='function')
maincallback({statuscode:3,status:"CLOSED",message:"User closed subscription Opt-in"});if(_peD.getInputUrl('intermediate')&&!pe.isFirefoxPermissionDefaultQuiterUI()){pe.sendDataToBrowser();}
if(_peE.sT=="https"&&_peE.swSupport==1)
_peD.widget.addHtml(maincallback);if(pe.isFirefoxPermissionDefaultQuiterUI()){try{var optinSetting=_peD.optinSettings();var optInTitle=optinSetting.optin_title||"Please confirm you would like to get notifications.";_peD.widget.addBoxHtml(maincallback);widgetBtnBox=_peD.getId("PE-button-box");widgetDeny=_peD.getId("PE-cancel-btn");widgetAllow=_peD.getId("PE-retry-btn");widgetMessage=_peD.getId("PE-chicklet-inst-modal-body-message");widgetBtnBox.style.padding="20px";widgetAllow.innerHTML=optinSetting.optin_allow_btn_txt||"Allow";widgetDeny.innerHTML=optinSetting.optin_close_btn_txt||"Deny";widgetMessage.innerHTML='<p style="font-size:18px;line-height:24px;text-align:center">'+optInTitle+'</p>';}
catch(error){console.log(error);}}},permissionGranted:function(subscription,maincallback){if(_peD.getInputUrl('recover_subscriber_from_iframe'))
_peE.refToken=true;_peD.insertFile('js','pushengage-geo',false,function(res){var ip=false;var geoInfo;if(typeof peGeoInfo=="undefined")
geoInfo=_peD.modifyGeo();else
{geoInfo=_peD.modifyGeo(peGeoInfo);ip=geoInfo.geobytesipaddress;}
var availScreen=screen.availWidth+'*'+screen.availHeight;var data={relApiPath:'/subscriber/add',reqData:{site_id:_peSd.site.sSi,browser_info:{device_type:_peE.bW.name,browser_version:_peE.bW.version,user_agent:navigator.userAgent,language:navigator.language,total_scr_width_height:screen.width+'*'+screen.height,available_scr_width_height:availScreen,colour_resolution:screen.pixelDepth,host:location.host,device:_peE.dT,pe_ref_url:_peE.subUrl},subscription:subscription,subscription_url:_peE.subUrl,geo_info:geoInfo,token_refresh:_peE.refToken,}};if(_peSd.subA&&!_peE.refToken){data.reqData.optin_type=_peD.subOptinType();if(_peE.widgetClick)
data.reqData.widget_optin_type=_peD.widget.optinType;}
if(_peSd.welcomeNoti&&(_peSd.welcomeNoti.welcome_enabled=="true"||_peSd.welcomeNoti.welcome_enabled==true)&&!_peE.refToken){pe.welcomeNoti(function(res){});}
_peD.sendRequestToServer(data,function(res){var resData=JSON.parse(res);var resObj={statuscode:0,message:"Something went wrong"};if(resData.data&&resData.data.hasOwnProperty('subscriber_hash')&&resData.data.subscriber_hash.length==64){if(!_peE.refToken&&_peD.subOptinType()!=4){_peD.optinAnalytics({allow_2:true,optin_2:true});}
var currentTime=new Date().getTime();var subCookieData=JSON.stringify({bv:_peE.bW.version,ip:{v:ip,d:currentTime},l:navigator.language,s:availScreen,tz:data.reqData.geo_info.geobytestimezone});_peD.resetStorage();_peD.cookie.set([['peclosed',true,_peD.cookie.global,'/','cookie'],['PushSubscriberID',_peD.deviceToken.value,false,'/','local'],['PushSubscriberHash',resData.data.subscriber_hash,false,'/','local'],['PushSubscriberStatus','SUBSCRIBED',_peD.cookie.global,'/','cookie'],['PushPersonalNotificationStatus',true,false,'/','local'],['PeSubData',subCookieData,false,'/','local'],['PushOptinReminder',JSON.stringify({}),false,'/','local'],]);_peD.cookie.remove([["PushSubscribeWidgetAnalytics","local"]])
if(_peE.sT=="https"&&_peE.swSupport==1&&typeof _pe!="undefined")
_pe.subMangWidget.addHtml(maincallback);switch(resData.error_code){case 0:resObj.statuscode=1;resObj.status="SUBSCRIBED";resObj.message="User subscribed sucessfully";resObj.subscriber_hash=resData.data.subscriber_hash;resObj.data={geoInfo:pe.formatGeoInfo()};}
if(_peE.subSegment){var segmentArr=_peE.subSegment.split(",");var segData={relApiPath:'/subscriber/segments/add',reqData:{segment:segmentArr,device_token_hash:_peD.cookie.get('PushSubscriberHash')}}
_peD.sendRequestToServer(segData,function(res){if(typeof maincallback=='function')maincallback(resObj);if(_peD.getInputUrl('intermediate')){pe.sendDataToBrowser();}});}
else{if(typeof maincallback=='function')maincallback(resObj);if(_peD.getInputUrl('intermediate')){pe.sendDataToBrowser();}}}
else if(_peD.getInputUrl('intermediate')&&window.opener)window.close();});});},welcomeNoti:function(callback){var options={body:_peSd.welcomeNoti.notification_message,tag:'welcome_notification'+_peSd.site.sSi,icon:_peSd.site.sI,data:_peSd.welcomeNoti.notification_url};if(_peE.bW.name=="Safari"&&Notification.permission==="granted"){var welcomeNoti=new Notification(_peSd.welcomeNoti.notification_title,options);welcomeNoti.onclick=function(event){event.preventDefault();window.open(_peSd.welcomeNoti.notification_url,'_blank');welcomeNoti.close();}
return(typeof callback=='function')?callback(true):true;}
else{var subApi;if(_peD.merchantSettings.sm('scope')){subApi=navigator.serviceWorker.ready;}
else{subApi=navigator.serviceWorker.register(_peD.merchantSettings.sm('worker'));}
subApi.then(function(registration){if(Notification.permission=='granted')
registration.showNotification(_peSd.welcomeNoti.notification_title,options).then(function(){return(typeof callback=='function')?callback(true):true;});});}},sendDataToBrowser:function(){var state=_peD.cookie.get('PushSubscriberStatus');if(!state){switch(Notification.permission){case"granted":state="SUBSCRIBED";break;case"denied":state="DENIED";break;default:state="CLOSED";}}
var data={PushSubscriberID:_peD.cookie.get('PushSubscriberID'),PushSubscriberHash:_peD.cookie.get('PushSubscriberHash'),state:state,source:"subscribe",postOrigin:"opener",geoInfoData:{geoInfo:pe.formatGeoInfo()},subCookieData:_peD.cookie.get('PeSubData')};if(window.opener)
{window.opener.postMessage(JSON.stringify(data),_peE.subUrl);window.close();}
else if(_peD.getInputUrl('recover_subscriber')){data.postOrigin="iframe";parent.postMessage(JSON.stringify(data),'*');}
else if(_peD.getInputUrl('refer'))window.location=_peE.subUrl;else if(_peD.getInputUrl('recover_subscriber_from_iframe')){data.postOrigin="iframe";data.subscriberOrigin="recoverSubscriber";parent.postMessage(JSON.stringify(data),'*');}},formatGeoInfo:function(){return{country:(typeof peGeoInfo!="undefined"&&typeof peGeoInfo.geobytescountry!="undefined")?peGeoInfo.geobytescountry:"",state:(typeof peGeoInfo!="undefined"&&typeof peGeoInfo.geobytesregion!="undefined")?peGeoInfo.geobytesregion:"",city:(typeof peGeoInfo!="undefined"&&typeof peGeoInfo.geobytescity!="undefined")?peGeoInfo.geobytescity:""}},isFirefoxPermissionDefaultQuiterUI:function(){var browser=_peE.bW;if(Notification.permission=="default"&&browser.name=="Firefox"&&browser.version>71){return true;}else{return false;}},optinSubscriptionReminder:{clearReminderId:false,getStorageData:function(){var reminderInfo={count:0,time:0};try{reminderInfo=_peD.cookie.get("PushOptinReminder");reminderInfo=reminderInfo?JSON.parse(reminderInfo):{};reminderInfo.count=Number(reminderInfo.count)||0;reminderInfo.time=Number(reminderInfo.time)||0;}catch(e){console.log(e.message);}
return reminderInfo;},setInfoToStorage:function(){try{var reminderInfo=pe.optinSubscriptionReminder.getStorageData();var reminderCount=1+reminderInfo.count;var currentTime=new Date().getTime();_peD.cookie.set([['PushOptinReminder',JSON.stringify({count:reminderCount,time:currentTime}),false,'/','local'],]);}
catch(e){console.log(e.message);}},getDelay:function(){var optinSubscriptionReminder=_peSd.optinSubscriptionReminder;var delay=optinSubscriptionReminder.show_after_initial_delay;try{var reminderInfo=pe.optinSubscriptionReminder.getStorageData();if(reminderInfo.time){var diffDelay=(new Date().getTime()-new Date(reminderInfo.time))/1000;delay=optinSubscriptionReminder.show_again_after-diffDelay;delay=(delay>0)?delay:0;}}
catch(e){console.log(e.message);}
return delay;},status:function(){var status=false;var reminderId=_peD.getId("pushengage-optin-reminder");var optinSubscriptionReminder=_peSd.optinSubscriptionReminder;var storageData=pe.optinSubscriptionReminder.getStorageData();if(!reminderId&&optinSubscriptionReminder&&optinSubscriptionReminder.enabled&&(!optinSubscriptionReminder.max_prompt||storageData.count<optinSubscriptionReminder.max_prompt)&&_peE.dT==="desktop"&&!_peSd.overlay.status&&_peD.isQuiterUi()){status=true;}
return status;},reminder:function(){var optinSubscriptionReminder=_peSd.optinSubscriptionReminder;var cssPlacement;switch(optinSubscriptionReminder.placement){case"center":cssPlacement="right:0px;left:0px;margin:0 auto;top:135px;";break;case"left":cssPlacement="left:100px;top:135px;";break;case"bottom_right":cssPlacement="bottom:0;right:100px;";break;case"bottom_left":cssPlacement="bottom:0;left:100px;";break;default:cssPlacement="right:100px;top:135px;";}
var imageUrl=pe.staticStorageUrl+'/site_assets/img/reminder-chrome.png';if(_peE.bW.name==="Firefox"){imageUrl=pe.staticStorageUrl+'/site_assets/img/reminder-firefox.png';}
try{var cssContent='<style id="pushengage-optin-reminder-style">#pushengage-optin-reminder{'+cssPlacement+'position:fixed;width:260px;box-shadow:0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.12),0 1px 5px 0 rgba(0,0,0,.2);background:'+optinSubscriptionReminder.background+';color:'+optinSubscriptionReminder.color+';border-radius:5px}#pushengage-optin-reminder img,#pushengage-optin-reminder p{margin:0;padding:0}#pushengage-optin-reminder p{margin:8px 10px;line-height:22px;max-height:350px;overflow:hidden;text-overflow:ellipsis;}#pushengage-optin-reminder img{width: 100%;border-radius: 5px 5px 0 0;}#pushengage-optin-reminder-close{max-width:200px;max-height:30px;float:right;padding:0 7px;min-width:60px;text-align:center;border-radius:2px;cursor:pointer;font-size:15px;overflow:hidden;text-overflow:ellipsis;line-height:30px;box-shadow:0 1px 3px 0 rgba(0,0,0,.2),0 1px 1px 0 rgba(0,0,0,.14),0 2px 1px -1px rgba(0,0,0,.12);background:'+optinSubscriptionReminder.button_background+';color:'+optinSubscriptionReminder.button_color+';margin:0 8px 12px 0}</style>';var htmlContent="<div id='pushengage-optin-reminder'><img src='"+imageUrl+"'/><p>"+optinSubscriptionReminder.description+"</p><div id='pushengage-optin-reminder-close'>"+optinSubscriptionReminder.button+"</div></div>";var delay=pe.optinSubscriptionReminder.getDelay();pe.optinSubscriptionReminder.clearReminderId=setTimeout(function(){var body=document.getElementsByTagName("BODY")[0];body.insertAdjacentHTML('beforeend',cssContent);body.insertAdjacentHTML('beforeend',htmlContent);var closeReminder=_peD.getId("pushengage-optin-reminder-close");if(closeReminder){closeReminder.addEventListener('click',function(){pe.optinSubscriptionReminder.clearReminder();});}
pe.optinSubscriptionReminder.setInfoToStorage();},delay*1000);}
catch(error){console.log(error.message);}},clearReminder:function(){var timeoutID=pe.optinSubscriptionReminder.clearReminderId;if(timeoutID){clearTimeout(pe.optinSubscriptionReminder.clearReminderId);}
_peD.rvHtml(_peD.getId("pushengage-optin-reminder"));_peD.rvHtml(_peD.getId("pushengage-optin-reminder-style"));}}}}
catch(e){console.log(e);}